# Generated by Django 5.2.3 on 2025-06-11 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteersignup',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='volunteersignup',
            name='phone',
        ),
        migrations.AlterField(
            model_name='volunteersignup',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteeropportunity'),
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
