# Generated by Django 5.2.3 on 2025-06-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('envelope_number', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('method', models.CharField(choices=[('envelope', 'Envelope'), ('cash', 'Cash'), ('online', 'Online'), ('check', 'Check')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
