# Generated by Django 5.2.3 on 2025-06-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('request', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('answered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
